version: '3.9'

services:
  web:
    build: .
    command: python /bookstore_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - F:\workspace\django\bookstore_project
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data: F:\workspace\PostgreSQL\13\data
volumes:
  postgres_data: